version: '3.7'
services:
  zephyr_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ZEPHYR_BRANCH: $ZEPHYR_BRANCH
        ZEPHYR_URL: $ZEPHYR_URL
        SDK_VERSION: $SDK_VERSION
        CMAKE_VERSION: $CMAKE_VERSION
        USERNAME: $USERNAME
        GCC_ARM_NAME: $GCC_ARM_NAME
    container_name: zephyrApp
    volumes:
      - .:/home/$USERNAME/workdir
      - /dev:/dev
    stdin_open: true
    tty: true
